### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mehakkhan7** [cauchyturing/UCR_Time_Series_Classification_Deep_Learning_Baseline#5]
I am facing this issue after running resnet code, MLP and FCN is working fine. could you please help?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-f66e1600cf25> in <module>()
    138     x_test = x_test.reshape(x_test.shape + (1, 1,))
    139 
--> 140     x, y = build_resnet(x_train.shape[1:], 64, nb_classes)
    141     model = Model(input=x, output=y)
    142     optimizer = keras.optimizers.Adam()

<ipython-input-2-f66e1600cf25> in build_resnet(input_shape, n_feature_maps, nb_classes)
     42         shortcut_y = keras.layers.normalization.BatchNormalization()(x)
     43     print('Merging skip connection')
---> 44     y = merge([shortcut_y, conv_z], mode='sum')
     45     y = Activation('relu')(y)
     46 

TypeError: 'module' object is not callable

**Comment by WYF1118** [comment]
replace 44   y = merge([shortcut_y, conv_z], mode='sum')          as       y = add([shortcut_y, conv_z])

**Comment by Mehakkhan7** [comment]
> replace 44 y = merge([shortcut_y, conv_z], mode='sum') as y = add([shortcut_y, conv_z])

It didn't work for me

**Comment by joe-hu** [comment]
I am facing the same problem. Have you solved this problem?@Mehakkhan7

**Comment by cauchyturing** [comment]
> I am facing this issue after running resnet code, MLP and FCN is working fine. could you please help?
> 
> TypeError Traceback (most recent call last)
> in ()
> 138 x_test = x_test.reshape(x_test.shape + (1, 1,))
> 139
> --> 140 x, y = build_resnet(x_train.shape[1:], 64, nb_classes)
> 141 model = Model(input=x, output=y)
> 142 optimizer = keras.optimizers.Adam()
> 
> in build_resnet(input_shape, n_feature_maps, nb_classes)
> 42 shortcut_y = keras.layers.normalization.BatchNormalization()(x)
> 43 print('Merging skip connection')
> ---> 44 y = merge([shortcut_y, conv_z], mode='sum')
> 45 y = Activation('relu')(y)
> 46
> 
> TypeError: 'module' object is not callable

Update the code with tensorflow 1.13.1 and fix a bunch of vintage dependencies, should work now

**Comment by Mehakkhan7** [comment]
> I am facing the same problem. Have you solved this problem?@Mehakkhan7

replace 44 y = merge([shortcut_y, conv_z], mode='sum') as y = add([shortcut_y, conv_z])

this worked for me.

**Comment by joe-hu** [comment]
replace 44 y = merge([shortcut_y, conv_z], mode='sum') as y = add([shortcut_y, conv_z]). it didn't work for me. i got a NameError: name 'add' is not defined. I have tried searching for solution, but all of them cann't work for me. i am new to python and  still don't know how to deal with this error. @Mehakkhan7

**Comment by joe-hu** [comment]
My tensorflow version is 1.13.1, it still can't work. which vintage dependencies should i fix?@cauchyturing

**Comment by joe-hu** [comment]
The updated code worked for me. Thank you very much!
